### ISSUE TITLE
re-order some components

### ISSUE THREAD

**Issue by danijeljw** [oseyx/sadmin_V5#29]
The requirement to move files that are being ignored should be processed from the server's working directory.

As this is currently actioned first, any files that are removed then re-added by HCM will re-add and be moved to the `$VarWdir`

To Do:
- [x] re-arrange the behaviours

**Comment by oseyx** [comment]
- moved `. $PSSCriptRoot\srv\getset.ps1` up
- moved `. $PSScriptRoot\cfg\RemoveIgnoreFiles.ps1` down
